---
# task/debian file for manage_repositories
- name: "Configure ubuntu main repositories into sources.list"
  vars:
    repositories: "{{ manage_repositories_default_repo }}"
  ansible.builtin.template:
    src: "sources.list.j2"
    dest: "{{ manage_repositories_default_repo_location }}"
    mode: '0644'
    owner: root
    group: root
  notify:
    - "debian-based-cache-update"
