---
# task/main file for manage_repositories
- name: "Load variables"
  ansible.builtin.include_vars:
    file: "{{ ansible_distribution|lower }}.yml"

- name: "Import prerequisites.yml"
  ansible.builtin.include_tasks: prerequisites.yml

- name: "Import main repositories for {{ ansible_distribution|lower }}"
  ansible.builtin.include_tasks: "main_repositories.yml"
  when: manage_repositories_enable_default_repo

- name: "Import custom_repositories.yml"
  ansible.builtin.include_tasks: custom_repositories.yml
  when: manage_repositories_enable_custom_repo

- name: "Update apt caches"
  ansible.builtin.meta: flush_handlers
