---
# task/prerequisites file for manage_repositories
- name: "Install python dependencies"
  ansible.builtin.include_role:
    name: ednz_cloud.manage_apt_packages
  vars:
    manage_apt_packages_list: "{{ manage_repositories_required_packages }}"
