---
manage_repositories_enable_default_repo: true
manage_repositories_enable_custom_repo: true
manage_repositories_custom_repo:
  - uri: "https://apt.releases.hashicorp.com"
    gpg_key: "https://apt.releases.hashicorp.com/gpg"
    comments: "hashicorp repository"
    type: "deb"
    suites: "{{ ansible_distribution_release }}"
    components: "main"
    filename: "hashicorp"
  - uri: "https://download.docker.com/linux/{{ ansible_distribution|lower }}"
    gpg_key: "https://download.docker.com/linux/{{ ansible_distribution|lower }}/gpg"
    comments: "{{ ansible_distribution|lower }} docker repository"
    type: "deb"
    suites: "{{ ansible_distribution_release }}"
    components: "stable"
    filename: "docker"
